---
# golangci-lint configuration
#
linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - bodyclose
    - dogsled
    - gomnd
    - gosec
    - misspell
    - rowserrcheck
    - unconvert
    - unparam
    - whitespace
linters-settings:
  gomnd:
    settings:
      mnd:
        checks:
          - argument
          - case
          - condition
          - return
  govet:
    check-shadowing: true
  unparam:
    check-exported: true
